"""
Pydantic schemas for request and response validation.

ArticleInput  – what the caller sends to /extract-event
ExtractedEvent – what the endpoint returns
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, field_validator


class ArticleInput(BaseModel):
    """Incoming news article payload."""

    title: str = Field(..., description="Headline of the article")
    source: str = Field(..., description="Publisher / news source name")
    published_at: Optional[str] = Field(None, description="ISO-8601 timestamp or free-text date")
    url: Optional[str] = Field(None, description="Canonical URL of the article")
    body: str = Field(..., description="Full body text of the article")

    model_config = {"str_strip_whitespace": True}


class ExtractedEvent(BaseModel):
    """
    Structured investment-research event extracted from a news article.

    All list fields default to empty lists so partial extractions are still
    schema-valid. severity and novelty are constrained to [0, 1].
    """

    event_type: str = Field(..., description="High-level category of the event (e.g. 'geopolitical_conflict')")
    entities: list[str] = Field(default_factory=list, description="Named entities: companies, countries, people")
    region: list[str] = Field(default_factory=list, description="Geographic regions affected")
    summary: str = Field(..., description="One-to-two sentence plain-English summary")
    severity: float = Field(..., description="Impact severity score in [0, 1]")
    novelty: float = Field(..., description="Novelty / surprise score in [0, 1]")
    channels: list[str] = Field(default_factory=list, description="Transmission channels (e.g. 'energy_prices', 'supply_chain')")
    time_horizon: str = Field(..., description="Expected duration of impact: 'short', 'medium', or 'long'")
    affected_sectors: list[str] = Field(default_factory=list, description="GICS-style sector labels")
    evidence_statements: list[str] = Field(default_factory=list, description="Direct quotes or paraphrases supporting the event")
    uncertainty_notes: list[str] = Field(default_factory=list, description="Caveats, conflicting signals, or unknowns")

    @field_validator("severity", "novelty")
    @classmethod
    def must_be_unit_interval(cls, v: float, info) -> float:
        if not (0.0 <= v <= 1.0):
            raise ValueError(f"{info.field_name} must be between 0 and 1, got {v}")
        return v

    @field_validator("time_horizon")
    @classmethod
    def must_be_valid_horizon(cls, v: str) -> str:
        allowed = {"short", "medium", "long"}
        if v not in allowed:
            raise ValueError(f"time_horizon must be one of {allowed}, got '{v}'")
        return v


class TradeIdea(BaseModel):
    """
    A single candidate trade idea produced by the rules + idea generation layer.

    confidence is constrained to [0, 1].
    direction must be 'long' or 'short'.
    """

    asset: str = Field(..., description="Ticker, ETF, or asset identifier (e.g. 'XLE', 'gold_spot')")
    direction: str = Field(..., description="Trade direction: 'long' or 'short'")
    confidence: float = Field(..., description="Conviction score in [0, 1]")
    horizon: str = Field(..., description="Expected holding period: 'short', 'medium', or 'long'")
    thesis: str = Field(..., description="One-sentence investment thesis")
    supporting_factors: list[str] = Field(default_factory=list, description="Evidence and corroborating signals")
    risk_flags: list[str] = Field(default_factory=list, description="Key risks that could undermine the trade")
    invalidation_conditions: list[str] = Field(default_factory=list, description="Observable conditions that would invalidate the thesis")

    @field_validator("confidence")
    @classmethod
    def confidence_must_be_unit_interval(cls, v: float) -> float:
        if not (0.0 <= v <= 1.0):
            raise ValueError(f"confidence must be between 0 and 1, got {v}")
        return v

    @field_validator("direction")
    @classmethod
    def direction_must_be_valid(cls, v: str) -> str:
        allowed = {"long", "short"}
        if v not in allowed:
            raise ValueError(f"direction must be one of {allowed}, got '{v}'")
        return v


class AnalyzeArticleResponse(BaseModel):
    """
    Top-level response from POST /analyze-article.

    Bundles the extracted event, all matched rule IDs, and the generated
    trade ideas into a single validated response object.
    """

    event: ExtractedEvent = Field(..., description="Structured event extracted from the article")
    ideas: list[TradeIdea] = Field(default_factory=list, description="Candidate trade ideas generated by the rules engine")
    matched_rule_ids: list[str] = Field(default_factory=list, description="IDs of all rules that fired against this event")
